### ISSUE TITLE
This doesn't appear to work anymore with Google

### ISSUE THREAD

**Issue by ursomniac** [agiliq/django-graphos#146]
The google.setOnLoadCallback()  call returns "google is not defined".  (This is on software using this package that has been working fine - until recently with no changes.)

Is this related to Google's changes to policy?

Is this package being supported anymore?

**Comment by ursomniac** [comment]
I think I figured out what to change...   Whew.

**Comment by mlemosf** [comment]
@ursomniac I've stumbled upon the same problem on my project. I know it's been more than 2 years, but can you tell me what you did that solved the problem?
