### ISSUE TITLE
Separate html and script from template

### ISSUE THREAD

**Issue by 8ksoft** [agiliq/django-graphos#23]
Hi,

It might be useful to have {{ chart.as_html }} and {{ chart.as_script }} or something similar in order to collect all scripts at the end of the page.  The first method would make the divs will be rendered and the second will show the script.
When we load jquery at botton of the page, we got ReferenceError for $ function, because the script function appears before than the chart js library was loaded.

Thanks for consider this option!

**Comment by tkwon** [comment]
This PR is ready, just not merged. I hope someone can merge it because I'm eager to use this feature.

**Comment by akshar-raaj** [comment]
@8ksoft @tkwon The PR for this is merged into master. Can you check if this is what you wanted. Please feel free to reopen this issue if you think it's not fixed.

**Comment by akshar-raaj** [comment]
@8ksoft @tkwon After merging PR for suggested changes, now the following can be done in the template:

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
          google.load("visualization", "1", {packages:["corechart"]});
    </script>
    {{chart.render_js}}
    {{chart.render_html}}

This assumes that view has following code:

    sd = SimpleDataSource(data)
    chart = gchart.LineChart(sd)
    context = {'chart': chart}
    return render(request, 'some_template.html', context)

**Comment by tkwon** [comment]
Great!
