### ISSUE TITLE
ImportError: No module named local

### ISSUE THREAD

**Issue by renjithsraj** [agiliq/django-graphos#28]
I try to run this same demo project with my local machine i install the packages which you mention in the requirements.txt but its showing in this errror , i dont know why this happen , if this issue simple means please let me know.

**Comment by wynnfynn** [comment]
try it like this
cd    django-graphos-master/demo_project/demo_project/settings
cp  local.py-dist local.py

**Comment by akshar-raaj** [comment]
@renjithsraj The solution provided by @wynnfynn should work. You need to copy local.py-dist into local.py
