### ISSUE TITLE
Support moved to https://github.com/ModusVivendi/django-graphos

### ISSUE THREAD

**Issue by ModusVivendi** [agiliq/django-graphos#38]
Since the organization that owns this repo seems to have discontinued support, I have forked this repo at https://github.com/ModusVivendi/django-graphos and merged all of the recent pull requests.  My fork is available on pypi as django-graphos-3.

**Comment by akshar-raaj** [comment]
@ModusVivendi Thanks for this. We have been busy for some time and so could not merge the PRs, all the PRs are merged now. Please feel free to reopen this issue if there is any actionable item for me here, else I am closing this issue.
