### ISSUE TITLE
Add documentation on how to handle non serializable fields

### ISSUE THREAD

**Issue by akshar-raaj** [agiliq/django-graphos#50]
datetime.datetime() is non JSON serializable. So json data for this can't be passed to graphos renderers. See https://github.com/agiliq/django-graphos/issues/35 for detail.

The workaround for this is to write a subclass which inherits from SimpleDataSource or ModelDataSource and override get_data(). The workaround is already mentioned in a comment of https://github.com/agiliq/django-graphos/issues/35. This workaround should be added in README.md.

**Comment by luzfcb** [comment]
It would be nice if the documentation was also published and activated the automatic update in https://readthedocs.io/
