### ISSUE TITLE
Are there any examples of creating a chart with Highcharts?  I can't get anything to appear.

### ISSUE THREAD

**Issue by ursomniac** [agiliq/django-graphos#79]
I've successfully used Graphos to create charts with Google.
But I can't seem to make it work with Highcharts.

I'm loading the JS library:
`<script src="http://code.highcharts.com/highcharts.js"></script>`

and am importing LineChart `graphos.renderers.highcharts` in the view.

Nothing renders on the page...   What am I missing?

**Comment by akshar-raaj** [comment]
@ursomniac Are you seding LineChart object to the template context and doing {{chart.as_html}}?

**Comment by akshar-raaj** [comment]
@ursomniac You should run demo_project of graphos, part of this repository. demo_project has examples for highcharts.
