### ISSUE TITLE
What about scatter plots

### ISSUE THREAD

**Issue by ursomniac** [agiliq/django-graphos#82]
I'm impressed with the scope of chart types that are available, but I'm surprised to not find that scatter plots are among them...

Am I missing something?   If not, is this something that will be added anytime soon?

**Comment by akshar-raaj** [comment]
@ursomniac We support Scatter chart for highcharts. https://github.com/agiliq/django-graphos/blob/master/graphos/renderers/highcharts.py#L102

If you want it for some other renderer, can you add it and open a Pull request. We would be glad to accept a PR for that :)
