### ISSUE TITLE
what is chart.as_html?

### ISSUE THREAD

**Issue by shubhpy** [agiliq/django-graphos#84]
def show_employee(request):
    emp = Employee.objects.raw('select id,job_title, count(job_title) as count_job_title from employee group by job_title order by count(job_title) desc,job_title desc limit 5')
    data_source = ModelDataSource(emp, fields=['job_title', 'count_job_title'],)
    line_chart = morris.LineChart(data_source)
    return render(request,'blog/show_employee.html',{'line_chart':line_chart})

{% extends 'blog/base.html' %}  

{% block content %}
    <div id="line_chart" class="well">
    {{ line_chart.as_html }}
    </div>
{% endblock %}

This does not show anything in graph??

**Comment by akshar-raaj** [comment]
@shubhpy Are you including morris javascript in your template or in blog/base.html?
